# Generated by Django 4.0.6 on 2022-07-11 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0002_alter_reservation_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motel',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='motel',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 5, 45, 27, 752428, tzinfo=utc)),
        ),
    ]
