# Generated by Django 4.0.6 on 2022-07-12 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0005_alter_motelimage_motel_alter_reservation_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2022, 7, 12, 7, 54, 23, 290034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='motel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='motel.motel'),
        ),
    ]
