# Generated by Django 4.0.6 on 2022-07-12 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('motel', '0006_alter_reservation_checkin_alter_room_motel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motelimage',
            name='motel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motelimages', to='motel.motel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2022, 7, 12, 7, 55, 9, 483446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationrooms', to='motel.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationusers', to='user.user'),
        ),
        migrations.AlterField(
            model_name='room',
            name='motel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='motel.motel'),
        ),
        migrations.AlterField(
            model_name='roomtheme',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomthemes', to='motel.room'),
        ),
        migrations.AlterField(
            model_name='roomtheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themerooms', to='motel.theme'),
        ),
    ]
