# Generated by Django 4.0.6 on 2022-07-12 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0007_alter_motelimage_motel_alter_reservation_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2022, 7, 12, 7, 58, 11, 470817, tzinfo=utc)),
        ),
    ]
