# Generated by Django 4.0.6 on 2022-07-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0008_alter_reservation_checkin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
